// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5voWOkUUxg9ZAZNUMFPCbHqoLJeJKyrg',
    appId: '1:974569562297:web:13458fe42ce7cf32473b68',
    messagingSenderId: '974569562297',
    projectId: 'witsnotes-c98b1',
    authDomain: 'witsnotes-c98b1.firebaseapp.com',
    storageBucket: 'witsnotes-c98b1.firebasestorage.app',
    measurementId: 'G-PT6P4K89N9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGja4sl2e1BFoGy-mZd99h8y_sT6oLf90',
    appId: '1:974569562297:android:2d2deaad1363c2fd473b68',
    messagingSenderId: '974569562297',
    projectId: 'witsnotes-c98b1',
    storageBucket: 'witsnotes-c98b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPEFjTk2qy8k5Gp_-PGxSkPLtLz-JAdc',
    appId: '1:974569562297:ios:e66f1f00842575f0473b68',
    messagingSenderId: '974569562297',
    projectId: 'witsnotes-c98b1',
    storageBucket: 'witsnotes-c98b1.firebasestorage.app',
    iosBundleId: 'com.example.witsNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHPEFjTk2qy8k5Gp_-PGxSkPLtLz-JAdc',
    appId: '1:974569562297:ios:e66f1f00842575f0473b68',
    messagingSenderId: '974569562297',
    projectId: 'witsnotes-c98b1',
    storageBucket: 'witsnotes-c98b1.firebasestorage.app',
    iosBundleId: 'com.example.witsNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5voWOkUUxg9ZAZNUMFPCbHqoLJeJKyrg',
    appId: '1:974569562297:web:87fcf1ff3d832a0e473b68',
    messagingSenderId: '974569562297',
    projectId: 'witsnotes-c98b1',
    authDomain: 'witsnotes-c98b1.firebaseapp.com',
    storageBucket: 'witsnotes-c98b1.firebasestorage.app',
    measurementId: 'G-0WNSZ3E3MC',
  );
}
